In [1]:
import sys, os
sys.path.append(os.pardir)  # 부모 디렉터리의 파일을 가져올 수 있도록 설정
import numpy as np
from common.functions import softmax, cross_entropy_error
from common.gradient import numerical_gradient


class simpleNet:
    def __init__(self):
        self.W = np.random.randn(2,3) # 정규분포로 초기화

    def predict(self, x):
        return np.dot(x, self.W)

    def loss(self, x, t):
        z = self.predict(x)
        y = softmax(z)
        loss = cross_entropy_error(y, t)

        return loss

In [2]:
net = simpleNet()
print(net.W)

[[-0.43602362 -2.20624998 -0.32415908]
 [ 1.58714147 -1.7750858  -0.62388752]]


In [3]:
x = np.array([0.6,0.9])
p = net.predict(x)
print(p)
print(np.argmax(p))

t = np.array([0,0,1])
print(net.loss(x,t))

[ 1.16681316 -2.9213272  -0.75599421]
0
2.0737805153546396


In [4]:
def f(W):
    return net.loss(x,t)
dW = numerical_gradient(f, net.W)
print(dW)

[[ 0.51592165  0.00865221 -0.52457386]
 [ 0.77388248  0.01297831 -0.78686079]]
